project_id = "nxsrxdlsnabpshncdplv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "https://dreamer-startup-portal-hub.vercel.app/"
additional_redirect_urls = ["https://dreamer-startup-portal-hub.vercel.app/"]
jwt_expiry = 3600
enable_signup = true
enable_manual_linking = false

[functions.handle-approval]
verify_jwt = false

[functions.send-approval-email]
verify_jwt = true

[functions.send-status-notification]
verify_jwt = false
  